version: '3.8'

networks:
    sender:
        external:
            name: sender

services:
    sender-postgres:
        image: postgres:15-alpine
        container_name: sender-postgres
        environment:
           - POSTGRES_USER=${POSTGRES_USER}
           - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
           - POSTGRES_DB=${POSTGRES_DB}
           - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
          - ./docker/mount:/var/lib/postgresql/data/pgdata
          - ./docker/postgres.conf:/etc/postgresql/postgresql.conf
        ports:
          - 5432:5432
        networks:
          - sender
        extra_hosts:
          host.docker.internal: host-gateway


